<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYD4UEPa\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYD4UEPa/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYD4UEPa.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYD4UEPa\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerYD4UEPa\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'YD4UEPa',
    'container.build_id' => '649b4e84',
    'container.build_time' => 1609676333,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYD4UEPa');
