twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    exception_controller: null
    globals:
        server_path: 'http://ec2-13-212-39-227.ap-southeast-1.compute.amazonaws.com/admin/public'
