<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Property extends \App\Entity\Property implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'Title', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'propertyStatus', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'propertyType', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'investment', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'ewa', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'furnishing', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'buildingName', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'location', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'value', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'Address', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'nearBy', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'bedRooms', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'BathRooms', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'AreaWidth', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'AreaHight', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'dateofupdated', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'map', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'Mortgage', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'features', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'createdBy', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'applicationAssets', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'propertyDetails', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'listingFor'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'Title', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'description', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'propertyStatus', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'propertyType', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'investment', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'ewa', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'furnishing', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'buildingName', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'location', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'value', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'Address', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'nearBy', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'bedRooms', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'BathRooms', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'AreaWidth', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'AreaHight', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'dateofupdated', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'map', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'Mortgage', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'features', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'createdBy', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'createdAt', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'applicationAssets', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'propertyDetails', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Property' . "\0" . 'listingFor'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Property $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getTitle(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitle', []);

        return parent::getTitle();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitle(string $Title): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitle', [$Title]);

        return parent::setTitle($Title);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescription(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescription', []);

        return parent::getDescription();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescription(string $description): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescription', [$description]);

        return parent::setDescription($description);
    }

    /**
     * {@inheritDoc}
     */
    public function getPropertyStatus(): ?\App\Entity\PropertyStatus
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPropertyStatus', []);

        return parent::getPropertyStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setPropertyStatus(?\App\Entity\PropertyStatus $propertyStatus): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropertyStatus', [$propertyStatus]);

        return parent::setPropertyStatus($propertyStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getPropertyType(): ?\App\Entity\PropertyType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPropertyType', []);

        return parent::getPropertyType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPropertyType(?\App\Entity\PropertyType $propertyType): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPropertyType', [$propertyType]);

        return parent::setPropertyType($propertyType);
    }

    /**
     * {@inheritDoc}
     */
    public function getInvestment(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInvestment', []);

        return parent::getInvestment();
    }

    /**
     * {@inheritDoc}
     */
    public function setInvestment(int $investment): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInvestment', [$investment]);

        return parent::setInvestment($investment);
    }

    /**
     * {@inheritDoc}
     */
    public function getEwa(): ?\App\Entity\Ewa
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getEwa', []);

        return parent::getEwa();
    }

    /**
     * {@inheritDoc}
     */
    public function setEwa(?\App\Entity\Ewa $ewa): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setEwa', [$ewa]);

        return parent::setEwa($ewa);
    }

    /**
     * {@inheritDoc}
     */
    public function getFurnishing(): ?\App\Entity\Furnishing
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFurnishing', []);

        return parent::getFurnishing();
    }

    /**
     * {@inheritDoc}
     */
    public function setFurnishing(?\App\Entity\Furnishing $furnishing): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFurnishing', [$furnishing]);

        return parent::setFurnishing($furnishing);
    }

    /**
     * {@inheritDoc}
     */
    public function getBuildingName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBuildingName', []);

        return parent::getBuildingName();
    }

    /**
     * {@inheritDoc}
     */
    public function setBuildingName(string $buildingName): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBuildingName', [$buildingName]);

        return parent::setBuildingName($buildingName);
    }

    /**
     * {@inheritDoc}
     */
    public function getLocation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLocation', []);

        return parent::getLocation();
    }

    /**
     * {@inheritDoc}
     */
    public function setLocation(string $location): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLocation', [$location]);

        return parent::setLocation($location);
    }

    /**
     * {@inheritDoc}
     */
    public function getValue(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getValue', []);

        return parent::getValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setValue(string $value): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setValue', [$value]);

        return parent::setValue($value);
    }

    /**
     * {@inheritDoc}
     */
    public function getAddress(): ?\App\Entity\Address
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAddress', []);

        return parent::getAddress();
    }

    /**
     * {@inheritDoc}
     */
    public function setAddress(?\App\Entity\Address $Address): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAddress', [$Address]);

        return parent::setAddress($Address);
    }

    /**
     * {@inheritDoc}
     */
    public function getNearBy(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNearBy', []);

        return parent::getNearBy();
    }

    /**
     * {@inheritDoc}
     */
    public function addNearBy(\App\Entity\NearBy $nearBy): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNearBy', [$nearBy]);

        return parent::addNearBy($nearBy);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNearBy(\App\Entity\NearBy $nearBy): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNearBy', [$nearBy]);

        return parent::removeNearBy($nearBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getBedRooms(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBedRooms', []);

        return parent::getBedRooms();
    }

    /**
     * {@inheritDoc}
     */
    public function setBedRooms(int $bedRooms): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBedRooms', [$bedRooms]);

        return parent::setBedRooms($bedRooms);
    }

    /**
     * {@inheritDoc}
     */
    public function getBathRooms(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBathRooms', []);

        return parent::getBathRooms();
    }

    /**
     * {@inheritDoc}
     */
    public function setBathRooms(string $BathRooms): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBathRooms', [$BathRooms]);

        return parent::setBathRooms($BathRooms);
    }

    /**
     * {@inheritDoc}
     */
    public function getAreaWidth(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreaWidth', []);

        return parent::getAreaWidth();
    }

    /**
     * {@inheritDoc}
     */
    public function setAreaWidth(int $AreaWidth): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAreaWidth', [$AreaWidth]);

        return parent::setAreaWidth($AreaWidth);
    }

    /**
     * {@inheritDoc}
     */
    public function getAreaHeight(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAreaHeight', []);

        return parent::getAreaHeight();
    }

    /**
     * {@inheritDoc}
     */
    public function setAreaHeight(int $AreaHeight): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAreaHeight', [$AreaHeight]);

        return parent::setAreaHeight($AreaHeight);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateofupdated(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateofupdated', []);

        return parent::getDateofupdated();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateofupdated(\DateTimeInterface $dateofupdated): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateofupdated', [$dateofupdated]);

        return parent::setDateofupdated($dateofupdated);
    }

    /**
     * {@inheritDoc}
     */
    public function getMap(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMap', []);

        return parent::getMap();
    }

    /**
     * {@inheritDoc}
     */
    public function setMap(string $map): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMap', [$map]);

        return parent::setMap($map);
    }

    /**
     * {@inheritDoc}
     */
    public function getMortgage(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMortgage', []);

        return parent::getMortgage();
    }

    /**
     * {@inheritDoc}
     */
    public function setMortgage(string $Mortgage): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMortgage', [$Mortgage]);

        return parent::setMortgage($Mortgage);
    }

    /**
     * {@inheritDoc}
     */
    public function getFeatures(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFeatures', []);

        return parent::getFeatures();
    }

    /**
     * {@inheritDoc}
     */
    public function setFeatures(string $features): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFeatures', [$features]);

        return parent::setFeatures($features);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedBy(): ?\App\Entity\Users
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedBy', []);

        return parent::getCreatedBy();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedBy(?\App\Entity\Users $createdBy): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedBy', [$createdBy]);

        return parent::setCreatedBy($createdBy);
    }

    /**
     * {@inheritDoc}
     */
    public function getCreatedAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreatedAt', []);

        return parent::getCreatedAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreatedAt(\DateTimeInterface $createdAt): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreatedAt', [$createdAt]);

        return parent::setCreatedAt($createdAt);
    }

    /**
     * {@inheritDoc}
     */
    public function getApplicationAssets(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getApplicationAssets', []);

        return parent::getApplicationAssets();
    }

    /**
     * {@inheritDoc}
     */
    public function addApplicationAsset(\App\Entity\ApplicationAssets $applicationAsset): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addApplicationAsset', [$applicationAsset]);

        return parent::addApplicationAsset($applicationAsset);
    }

    /**
     * {@inheritDoc}
     */
    public function removeApplicationAsset(\App\Entity\ApplicationAssets $applicationAsset): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeApplicationAsset', [$applicationAsset]);

        return parent::removeApplicationAsset($applicationAsset);
    }

    /**
     * {@inheritDoc}
     */
    public function getPropertyDetails(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPropertyDetails', []);

        return parent::getPropertyDetails();
    }

    /**
     * {@inheritDoc}
     */
    public function addPropertyDetail(\App\Entity\PropertyDetails $propertyDetail): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addPropertyDetail', [$propertyDetail]);

        return parent::addPropertyDetail($propertyDetail);
    }

    /**
     * {@inheritDoc}
     */
    public function removePropertyDetail(\App\Entity\PropertyDetails $propertyDetail): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removePropertyDetail', [$propertyDetail]);

        return parent::removePropertyDetail($propertyDetail);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(int $status): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getListingFor(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getListingFor', []);

        return parent::getListingFor();
    }

    /**
     * {@inheritDoc}
     */
    public function setListingFor(string $listingFor): \App\Entity\Property
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setListingFor', [$listingFor]);

        return parent::setListingFor($listingFor);
    }

}
